 # server configuration
 server:
  port: 80
  context-path: /
  # https configuration
  #ssl:
    #key-store: classpath:keystore.p12
    #key-password: activitycode
    #key-store-type: PKCS12
    #key-alias: tomcat

 spring:
  profiles:
    active: dev
  # datasource configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://220.200.150.44:3306/test?useSSL=false&useUnicode\=true&characterEncoding\=utf-8&autoReconnect\=true
    username: ycdata
    password: 2017.P@axTM7VF!pCKXEq.0406

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:hibernate:dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 100
      min-idle: 1
    database: 1
    password: admin@people.18

 logging:
#   path: /var/log
   file: weixin.log
   level: info
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss.SSS}-%L'
      file: '%d{yyyy-MM-dd HH:mm:ss.SSS}-%L'




